### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by ghost** [werxe/laravel-collection-macros#7]
I noticed you updated composer to require Laravel 7, which means it cannot be installed on any Laravel 6 projects. 

Is it possible to revert to a "either" constraint?

```json
"require": {
    "php": "^7.2.5",
    "illuminate/support": "^7.0 || ^6.1"
},
```

**Comment by brunogaspar** [comment]
Hi

You can use version 3 for Laravel 6

```
composer require werxe/laravel-collection-macros:^3.0
```
